version: '3.9'
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.104.0
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - '4317:4317'
      - '4318:4318'
  tempo:
    image: grafana/tempo:latest
    ports:
      - '3200:3200'
    command: [ '-config.file=/etc/tempo.yaml' ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
